-- V1 — Schéma initial de PresenceLab
-- Correspond à docs/diagrammes/D2_modele_donnees.md.
-- Règle d'équipe : une migration commitée n'est JAMAIS modifiée ; toute évolution = nouvelle migration.
-- SQL compatible PostgreSQL 16 et H2 2.x (mode PostgreSQL, utilisé par les tests).

CREATE TABLE promotion (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    CONSTRAINT uk_promotion_nom UNIQUE (nom)
);

CREATE TABLE etudiant (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom          VARCHAR(100) NOT NULL,
    promotion_id BIGINT       NOT NULL,
    CONSTRAINT fk_etudiant_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id)
);

-- RG1 : expiration_at = ouverture_at + 15 min · RG18 : code unique · H3 : fin de session = clôture
CREATE TABLE session_cours (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre         VARCHAR(200)             NOT NULL,
    promotion_id  BIGINT                   NOT NULL,
    code          VARCHAR(6)               NOT NULL,
    ouverture_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    expiration_at TIMESTAMP WITH TIME ZONE NOT NULL,
    cloture_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_session_code UNIQUE (code),
    CONSTRAINT fk_session_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id)
);

-- RG3 : une présence par étudiant et par session · RG4 : source ETUDIANT ou FORMATEUR
CREATE TABLE presence (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT                   NOT NULL,
    etudiant_id BIGINT                   NOT NULL,
    source      VARCHAR(10)              NOT NULL,
    marquee_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_presence_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT ck_presence_source CHECK (source IN ('ETUDIANT', 'FORMATEUR')),
    CONSTRAINT fk_presence_session FOREIGN KEY (session_id) REFERENCES session_cours (id),
    CONSTRAINT fk_presence_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)
);

-- RG6 : un exercice par étudiant et par session · D4 : statuts du cycle de vie
CREATE TABLE exercice (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT                   NOT NULL,
    etudiant_id BIGINT                   NOT NULL,
    lien        VARCHAR(500)             NOT NULL,
    statut      VARCHAR(30)              NOT NULL,
    depose_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_exercice_session_etudiant UNIQUE (session_id, etudiant_id),
    CONSTRAINT ck_exercice_statut CHECK (statut IN ('DEPOSE', 'EN_ATTENTE_RELECTURE', 'RELU')),
    CONSTRAINT fk_exercice_session FOREIGN KEY (session_id) REFERENCES session_cours (id),
    CONSTRAINT fk_exercice_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)
);

-- RG10 : un seul relecteur par exercice · RG13 : note entière 0..20 · RG14 : rendue_at renseigné = définitif
CREATE TABLE relecture (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id  BIGINT                   NOT NULL,
    relecteur_id BIGINT                   NOT NULL,
    note         INTEGER,
    commentaire  VARCHAR(1000),
    assignee_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    rendue_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_relecture_exercice UNIQUE (exercice_id),
    CONSTRAINT ck_relecture_note CHECK (note IS NULL OR (note >= 0 AND note <= 20)),
    CONSTRAINT fk_relecture_exercice FOREIGN KEY (exercice_id) REFERENCES exercice (id),
    CONSTRAINT fk_relecture_relecteur FOREIGN KEY (relecteur_id) REFERENCES etudiant (id)
);

CREATE INDEX idx_etudiant_promotion ON etudiant (promotion_id);
CREATE INDEX idx_session_promotion ON session_cours (promotion_id);
CREATE INDEX idx_relecture_relecteur ON relecture (relecteur_id);
